// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ehtoafcpotkhhuqhygzw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVodG9hZmNwb3RraGh1cWh5Z3p3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA1OTk2NzMsImV4cCI6MjA4NjE3NTY3M30.weWEdzVcuOZj2ZLV0fEUt4SYhBC2COHITSmCpeUDsRw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  }
});